writer: !console
  format: notImplemented
  
sources:

  - !jvm
    host  : 192.168.0.35
    port  : 9010
    metricsLists:
      - Memory
      
  - !weblogic
    host  : 192.168.0.35
    port  : 7001
    username: weblogic
    password: weblogic01
    metricsLists:
      - Memory
