writers: 
  - !console
    format: "$id $source.$metric $value $timestamp"
 
  - !graphite
    host: 172.0.0.1
    port: 2005
    
sources:

  - !jvm
    host  : 192.168.0.35
    port  : 9010
    prefix: java
    metrics:
      - Memory
      - MemoryPools
      - Threading
      
  - !weblogicDomain
    host  : 192.168.0.35
    port  : 7001
    username: weblogic
    password: weblogic01
    prefix: weblogic
    suffix: SUFFIX
    metrics:
      - Memory
      - MemoryPools
      - Threading
      
executorThreadPoolSize: 2
