writer: !console
  format: "$id $source.$metric $value $timestamp"
  
sources:

  - !jvm
    host  : 192.168.0.35
    port  : 9010
    prefix: java
    metricsLists:
      - Memory
      - MemoryPools
      - Threading
      
  - !weblogicDomain
    host  : 192.168.0.35
    port  : 7001
    username: weblogic
    password: weblogic01
    prefix: weblogic
    suffix: SUFFIX
    metricsLists:
      - Memory
      - MemoryPools
      - Threading
      
executorThreadPoolSize: 2
